In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from scipy import stats

In [6]:
df1 = pd.read_csv("Diabetes.csv")
# df2 = pd.read_csv("adult.csv")

print("Info")
print(df1.info())

print("\n Description")
print(df1.describe())

print("\n Unique value count")
total_count1 = df1["Urea"].value_counts()
print(total_count1)

print("\n Missing values greater then zero: ")
missing_val1 = df1.isnull().sum()
print(missing_val1[missing_val1 > 0])

Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1000 non-null   int64
 1   No_Pation  1000 non-null   int64
 2   Gender     1000 non-null   object
 3   AGE        1000 non-null   int64
 4   Urea       1000 non-null   float64
 5   Cr         1000 non-null   int64
 6   HbA1c      1000 non-null   float64
 7   Chol       1000 non-null   float64
 8   TG         1000 non-null   float64
 9   HDL        1000 non-null   float64
 10  LDL        1000 non-null   float64
 11  VLDL       1000 non-null   float64
 12  BMI        1000 non-null   float64
 13  CLASS      1000 non-null   object
dtypes: float64(8), int64(4), object(2)
memory usage: 109.5+ KB
None

 Description
                ID     No_Pation          AGE         Urea           Cr  \
count  1000.000000  1.000000e+03  1000.000000  1000.000000  1000.000000
mean    340.500000  2.705514e+05    53.528000     5.124743    68.943000
std     240.397673  3.380758e+06     8.799241     2.935165    59.984747
min       1.000000  1.230000e+02    20.000000     0.500000     6.000000
25%     125.750000  2.406375e+04    51.000000     3.700000    48.000000
50%     300.500000  3.439550e+04    55.000000     4.600000    60.000000
75%     550.250000  4.538425e+04    59.000000     5.700000    73.000000
max     800.000000  7.543566e+07    79.000000    38.900000   800.000000

             HbA1c         Chol           TG          HDL          LDL  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000
mean      8.281160     4.862820     2.349610     1.204750     2.609790
std       2.534003     1.301738     1.401176     0.660414     1.115102
min       0.900000     0.000000     0.300000     0.200000     0.300000
25%       6.500000     4.000000     1.500000     0.900000     1.800000
50%       8.000000     4.800000     2.000000     1.100000     2.500000
75%      10.200000     5.600000     2.900000     1.300000     3.300000
max      16.000000    10.300000    13.800000     9.900000     9.900000

              VLDL          BMI
count  1000.000000  1000.000000
mean      1.854700    29.578020
std       3.663599     4.962388
min       0.100000    19.000000
25%       0.700000    26.000000
50%       0.900000    30.000000
75%       1.500000    33.000000
max      35.000000    47.750000

 Unique value count
Urea
4.300     40
4.000     37
5.000     36
4.800     34
4.100     33
          ..
13.300     1
13.500     1
6.833      1
0.500      1
8.900      1
Name: count, Length: 110, dtype: int64

 Missing values greater then zero:
Series([], dtype: int64)

In [ ]:
df_copy = df1

# Initialize OrdinalEncoder
ordinal_encoder = OrdinalEncoder(categories=[["M", "F", "f"]])
# Fit and transform the data
df_copy["Gender_Encoded"] = ordinal_encoder.fit_transform(df_copy[["Gender"]])

# Initialize OneHotEncoder
onehot_encoder = OneHotEncoder()

# Fit and transform the "City" column
encoded_data = onehot_encoder.fit_transform(df1[["CLASS"]])

# Convert the sparse matrix to a dense array
encoded_array = encoded_data.toarray()

# Convert to DataFrame for better visualization
encoded_df = pd.DataFrame(encoded_array, columns=onehot_encoder.get_feature_names_out(["CLASS"]))
df_encoded = pd.concat([df_copy, encoded_df], axis=1)

df_encoded.drop("Gender", axis=1, inplace=True)
df_encoded.drop("CLASS", axis=1, inplace=True)

print(df_encoded. head())

    ID  No_Pation  AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL   BMI  \
0  502      17975   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
1  735      34221   26   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6  23.0
2  420      47975   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
3  680      87656   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
4  504      34223   33   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4  21.0

   Gender_Encoded  CLASS_N  CLASS_N   CLASS_P  CLASS_Y  CLASS_Y
0             1.0      1.0       0.0      0.0      0.0       0.0
1             0.0      1.0       0.0      0.0      0.0       0.0
2             1.0      1.0       0.0      0.0      0.0       0.0
3             1.0      1.0       0.0      0.0      0.0       0.0
4             0.0      1.0       0.0      0.0      0.0       0.0

In [ ]:
#Data Transformation
# Min-Max Scaler/Normalization (range 0-1)
normalizer = MinMaxScaler()
df_encoded[['Cr']] = normalizer.fit_transform(df_encoded[['Cr']])
df_encoded.head()

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,Gender_Encoded,CLASS_N,CLASS_N,CLASS_P,CLASS_Y,CLASS_Y
0,502,17975,50,4.7,0.050378,4.9,4.2,0.9,2.4,1.4,0.5,24.0,1.0,1.0,0.0,0.0,0.0,0.0
1,735,34221,26,4.5,0.070529,4.9,3.7,1.4,1.1,2.1,0.6,23.0,0.0,1.0,0.0,0.0,0.0,0.0
2,420,47975,50,4.7,0.050378,4.9,4.2,0.9,2.4,1.4,0.5,24.0,1.0,1.0,0.0,0.0,0.0,0.0
3,680,87656,50,4.7,0.050378,4.9,4.2,0.9,2.4,1.4,0.5,24.0,1.0,1.0,0.0,0.0,0.0,0.0
4,504,34223,33,7.1,0.050378,4.9,4.9,1.0,0.8,2.0,0.4,21.0,0.0,1.0,0.0,0.0,0.0,0.0

In [ ]:
# Standardization (mean=0, variance=1)
scaler = StandardScaler()
df_encoded[['AGE']] = scaler.fit_transform(df_encoded[['AGE']])
df_encoded.head()

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,Gender_Encoded,CLASS_N,CLASS_N,CLASS_P,CLASS_Y,CLASS_Y
0,502,17975,-0.401144,4.7,0.050378,4.9,4.2,0.9,2.4,1.4,0.5,24.0,1.0,1.0,0.0,0.0,0.0,0.0
1,735,34221,-3.130017,4.5,0.070529,4.9,3.7,1.4,1.1,2.1,0.6,23.0,0.0,1.0,0.0,0.0,0.0,0.0
2,420,47975,-0.401144,4.7,0.050378,4.9,4.2,0.9,2.4,1.4,0.5,24.0,1.0,1.0,0.0,0.0,0.0,0.0
3,680,87656,-0.401144,4.7,0.050378,4.9,4.2,0.9,2.4,1.4,0.5,24.0,1.0,1.0,0.0,0.0,0.0,0.0
4,504,34223,-2.334096,7.1,0.050378,4.9,4.9,1.0,0.8,2.0,0.4,21.0,0.0,1.0,0.0,0.0,0.0,0.0

In [ ]:
#Removing Outliers
# Outlier Detection and Treatment using IQR
df_encoded_copy1=df_encoded
df_encoded_copy2=df_encoded
df_encoded_copy3=df_encoded

Q1 = df_encoded_copy1['Cr'].quantile(0.25)
Q3 = df_encoded_copy1['Cr'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df_encoded_copy1['Cr'] = np.where(df_encoded_copy1['Cr'] > upper_bound, upper_bound,
                        np.where(df_encoded_copy1['Cr'] < lower_bound, lower_bound, df_encoded_copy1['Cr']))

print(df_encoded_copy1.head())

    ID  No_Pation       AGE  Urea        Cr  HbA1c  Chol   TG  HDL  LDL  VLDL  \
0  502      17975 -0.401144   4.7  0.050378    4.9   4.2  0.9  2.4  1.4   0.5
1  735      34221 -3.130017   4.5  0.070529    4.9   3.7  1.4  1.1  2.1   0.6
2  420      47975 -0.401144   4.7  0.050378    4.9   4.2  0.9  2.4  1.4   0.5
3  680      87656 -0.401144   4.7  0.050378    4.9   4.2  0.9  2.4  1.4   0.5
4  504      34223 -2.334096   7.1  0.050378    4.9   4.9  1.0  0.8  2.0   0.4

    BMI  Gender_Encoded  CLASS_N  CLASS_N   CLASS_P  CLASS_Y  CLASS_Y
0  24.0             1.0      1.0       0.0      0.0      0.0       0.0
1  23.0             0.0      1.0       0.0      0.0      0.0       0.0
2  24.0             1.0      1.0       0.0      0.0      0.0       0.0
3  24.0             1.0      1.0       0.0      0.0      0.0       0.0
4  21.0             0.0      1.0       0.0      0.0      0.0       0.0

In [ ]:
#Removing Outliers
# Z-score method

df_encoded_copy2['Cr_zscore'] = stats.zscore(df_encoded_copy2['Cr'])
df_encoded_copy2['Cr'] = np.where(df_encoded_copy2['Cr_zscore'].abs() > 3, np.nan, df_encoded_copy2['Cr'])  # Replace outliers with NaN
print(df_encoded_copy2.head())

    ID  No_Pation       AGE  Urea        Cr  HbA1c  Chol   TG  HDL  LDL  VLDL  \
0  502      17975 -0.401144   4.7  0.050378    4.9   4.2  0.9  2.4  1.4   0.5
1  735      34221 -3.130017   4.5  0.070529    4.9   3.7  1.4  1.1  2.1   0.6
2  420      47975 -0.401144   4.7  0.050378    4.9   4.2  0.9  2.4  1.4   0.5
3  680      87656 -0.401144   4.7  0.050378    4.9   4.2  0.9  2.4  1.4   0.5
4  504      34223 -2.334096   7.1  0.050378    4.9   4.9  1.0  0.8  2.0   0.4

    BMI  Gender_Encoded  CLASS_N  CLASS_N   CLASS_P  CLASS_Y  CLASS_Y   \
0  24.0             1.0      1.0       0.0      0.0      0.0       0.0
1  23.0             0.0      1.0       0.0      0.0      0.0       0.0
2  24.0             1.0      1.0       0.0      0.0      0.0       0.0
3  24.0             1.0      1.0       0.0      0.0      0.0       0.0
4  21.0             0.0      1.0       0.0      0.0      0.0       0.0

   Cr_zscore
0  -0.805658
1  -0.017005
2  -0.805658
3  -0.805658
4  -0.805658

In [ ]:
#Removing Outliers
# Median replacement for outliers
df_encoded_copy3['Cr_zscore'] = stats.zscore(df_encoded_copy3['Cr'])
median_salary = df_encoded_copy3['Cr'].median()
df_encoded_copy3['Cr'] = np.where(df_encoded_copy3['Cr_zscore'].abs() > 3, median_salary, df_encoded_copy3['Cr'])
print(df_encoded_copy3.head())

    ID  No_Pation       AGE  Urea        Cr  HbA1c  Chol   TG  HDL  LDL  VLDL  \
0  502      17975 -0.401144   4.7  0.050378    4.9   4.2  0.9  2.4  1.4   0.5
1  735      34221 -3.130017   4.5  0.070529    4.9   3.7  1.4  1.1  2.1   0.6
2  420      47975 -0.401144   4.7  0.050378    4.9   4.2  0.9  2.4  1.4   0.5
3  680      87656 -0.401144   4.7  0.050378    4.9   4.2  0.9  2.4  1.4   0.5
4  504      34223 -2.334096   7.1  0.050378    4.9   4.9  1.0  0.8  2.0   0.4

    BMI  Gender_Encoded  CLASS_N  CLASS_N   CLASS_P  CLASS_Y  CLASS_Y   \
0  24.0             1.0      1.0       0.0      0.0      0.0       0.0
1  23.0             0.0      1.0       0.0      0.0      0.0       0.0
2  24.0             1.0      1.0       0.0      0.0      0.0       0.0
3  24.0             1.0      1.0       0.0      0.0      0.0       0.0
4  21.0             0.0      1.0       0.0      0.0      0.0       0.0

   Cr_zscore
0  -0.805658
1  -0.017005
2  -0.805658
3  -0.805658
4  -0.805658

In [ ]:
df2 = pd.read_csv("adult.csv")

print("Info")
print(df2.info())

print("\n Description")
print(df2.describe())

print("\n Unique value count")
total_count2 = df2["income"].value_counts()
print(total_count2)

print("\n Missing values greater then zero: ")
missing_val2 = df2.isnull().sum()
print(missing_val2[missing_val2 > 0])

Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB
None

 Description
                age        fnlwgt  educational-num  capital-gain  \
count  48842.000000  4.884200e+04     48842.000000  48842.000000
mean      38.643585  1.896641e+05        10.078089   1079.067626
std       13.710510  1.056040e+05         2.570973   7452.019058
min       17.000000  1.228500e+04         1.000000      0.000000
25%       28.000000  1.175505e+05         9.000000      0.000000
50%       37.000000  1.781445e+05        10.000000      0.000000
75%       48.000000  2.376420e+05        12.000000      0.000000
max       90.000000  1.490400e+06        16.000000  99999.000000

       capital-loss  hours-per-week
count  48842.000000    48842.000000
mean      87.502314       40.422382
std      403.004552       12.391444
min        0.000000        1.000000
25%        0.000000       40.000000
50%        0.000000       40.000000
75%        0.000000       45.000000
max     4356.000000       99.000000

 Unique value count
income
<=50K    37155
>50K     11687
Name: count, dtype: int64

 Missing values greater then zero:
Series([], dtype: int64)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

df2 = pd.read_csv("adult.csv")
df_copy = df2

# Check if the column name is 'sex' instead of 'Gender'
if 'sex' in df_copy.columns and 'Gender' not in df_copy.columns:
    # If 'sex' column exists, rename it to 'Gender'
    df_copy = df_copy.rename(columns={'sex': 'Gender'})

# Initialize OrdinalEncoder
ordinal_encoder = OrdinalEncoder(categories=[["M", "F", "f"]])
# Fit and transform the data
df_copy["Gender_Encoded"] = ordinal_encoder.fit_transform(df_copy[["Gender"]])

# Initialize OneHotEncoder
onehot_encoder = OneHotEncoder()

# Fit and transform the "City" column
encoded_data = onehot_encoder.fit_transform(df1[["CLASS"]])

# Convert the sparse matrix to a dense array
encoded_array = encoded_data.toarray()

# Convert to DataFrame for better visualization
encoded_df = pd.DataFrame(encoded_array, columns=onehot_encoder.get_feature_names_out(["CLASS"]))
df_encoded = pd.concat([df_copy, encoded_df], axis=1)

df_encoded.drop("Gender", axis=1, inplace=True)
df_encoded.drop("CLASS", axis=1, inplace=True)

print(df_encoded. head())